apiVersion: rm.pivotaldata.io/v1alpha1
kind: HAWQResourcePool
metadata:
  name: hawq-resource-pool
  namespace: default
spec:
  namespace: default
  selector:
    matchLabels:
      resourcepool: hawq-resource-pool
  resourceCapacity:
    memory: 280000
    cpu: 60000
    ephemeralStorage: 100000
  image: hawqbeijing/hawq_for_rm:perf
  groups:
  - name: group1
    groupSize: NUM_GROUP_SIZE
    groupResourceLimit:
      memory: MEM_SIZE #2000
      cpu: CPU_SIZE #500
      ephemeralStorage: STORAGE_SIZE #1000
  #BestAllocatePolicy/FastAllocatePolicy/AIAllocatePolicy
  allocatePolicy: "FastAllocatePolicy"
