apiVersion: rm.pivotaldata.io/v1alpha1
kind: HAWQResourcePool
metadata:
  name: hawq-resource-pool
  namespace: default
spec:
  namespace: default
  selector:
    matchLabels:
      resourcepool: hawq-resource-pool
  resourceCapacity:
    memory: 1214400
    cpu: 160000
    ephemeralStorage: 30720000
    #  image: k8s.gcr.io/nginx-slim:0.8
  image: hawqbeijing/hawq_for_rm:vcheng_lsp_tmp
  groups:
  - name: group1
    groupSize: 20
    groupResourceLimit:
      memory: 1500
      cpu: 1000
      ephemeralStorage: 6000
  - name: group2
    groupSize: 10
    groupResourceLimit:
      memory: 2000
      cpu: 1500
      ephemeralStorage: 8000
  - name: group3
    groupSize: 20
    groupResourceLimit:
      memory: 1000
      cpu: 500
      ephemeralStorage: 4000
  - name: group4
    groupSize: 10
    groupResourceLimit:
      memory: 2000
      cpu: 2000
      ephemeralStorage: 8000

  #BestAllocatePolicy/FastAllocatePolicy/AIAllocatePolicy
  allocatePolicy: "FastAllocatePolicy"
